version: '3'

services:
  db:
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_as_cs
    container_name: mysql-local-nodejs
    image: mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always

  phpmyadmin:
    container_name: phpmyadmin-local-nodejs
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    restart: always
